# Generated by Django 3.1.6 on 2021-03-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eword', models.CharField(max_length=30, unique=True)),
                ('hword', models.CharField(max_length=30)),
                ('uses', models.CharField(max_length=120)),
                ('rword', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Words',
            },
        ),
    ]
