# Generated by Django 3.1.6 on 2021-05-28 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dicto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='words',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='upload/'),
            preserve_default=False,
        ),
    ]
